[[pages]]
name = "Section - Introduction :"
icon = "ğŸ“š"
is_section = true

[[pages]]
path = "add_step/home.py"
name = "Accueil"
icon = "ğŸ "

[[pages]]
path = "add_step/data_import.py"
name = "Importer votre fichier"
icon = "ğŸ“‚"

[[pages]]
name = "Section - Analyses :"
icon = "ğŸ“š"
is_section = true


[[pages]]
path = "add_step/audit_overview.py"
name = "Analyse - Vue globale"
icon = "ğŸ—ºï¸"

[[pages]]
path = "add_step/audit_page_location.py"
name = "Analyse - page_location"
icon = "ğŸ”—"

[[pages]]
path = "add_step/audit_event_params.py"
name = "Analyse - event_params"
icon = "ğŸ”—"

[[pages]]
path = "add_step/explore.py"
name = "Exploration libre"
icon = "ğŸ”"

[[pages]]
name = "Section - Autres :"
icon = "ğŸ“š"
is_section = true

[[pages]]
path = "add_step/thank_you.py"
name = "Remerciement"
icon = "ğŸ¤"

[[pages]]
path = "add_step/feedback.py"
name = "Demandez une feature"
icon = "ğŸ“¤"
